/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Abhishek
 */
public class CheckIn extends javax.swing.JFrame {
Connection cn;
ResultSet rs;
Statement stat;

    /**
     * Creates new form CheckIn
     */
    public CheckIn() {
        try{
        initComponents();
        this.setTitle("Hotel Management System");
        Date d=new Date();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jTextField1.setText(new SimpleDateFormat("yyyy-MM-dd").format(d));
        this.add(new JLabel(new ImageIcon("")));
        jLabel4.setLayout(new FlowLayout());
        Class.forName("com.mysql.cj.jdbc.Driver");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","root");
        stat=cn.createStatement();
        rs=stat.executeQuery("select c_id from customer order by c_id");
        while(rs.next())
        {
            jComboBox1.addItem(""+rs.getInt(1));
        }
        rs=stat.executeQuery("select room_no from room where r_status='AVAILABLE' order by room_no");
        if(rs.first())
        {
            this.setVisible(true);
            rs.first();
            jComboBox2.addItem(""+rs.getInt(1));
            while(rs.next())
            {
                jComboBox2.addItem(""+rs.getInt(1));
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"No Rooms Available.","Hotel Management System",JOptionPane.ERROR_MESSAGE);
            this.dispose();
            new MainMenu().setVisible(true);
        }
        }catch(Exception e){JOptionPane.showMessageDialog(null, e,"Hotel Management System",JOptionPane.ERROR_MESSAGE);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 250, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHECK IN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(760, 290, 261, 40);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(1180, 260, 164, 32);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 420, 300, 45);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ROOM NUMBER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 570, 301, 45);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(890, 420, 450, 45);

        jComboBox2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(890, 570, 450, 45);

        jButton1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 720, 301, 51);

        jButton2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(990, 720, 301, 51);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel_management/black-friday-buy-credit-card-34577.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 1930, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String c_id,room_no,cindate;
        int bill=0;
        c_id=(String)jComboBox1.getSelectedItem();
        room_no=(String)jComboBox2.getSelectedItem();
        cindate=jTextField1.getText();
        stat.executeUpdate("update room set r_status='NOTAVAILABLE',c_id="+c_id+" where room_no="+room_no+"");
        rs=stat.executeQuery("select bill_id from bill order by bill_id desc");
        if(rs.first())
        {
            rs.first();
            bill=rs.getInt(1);
            bill++;
        }
        else
            bill=1;
        stat.executeUpdate("insert into bill values("+bill+",'"+cindate+"',NULL,NULL,"+c_id+","+room_no+")");
        JOptionPane.showMessageDialog(null,"Check In Confirmed");
        this.dispose();
        new MainMenu().setVisible(true);
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new CheckIn();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
