/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel_management;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Abhishek
 */
public class UpdateCustomer extends javax.swing.JFrame {
Connection cn;
ResultSet rs;
Statement stat;
String s;
int count=0;
    /**
     * Creates new form UpdateCustomer
     */
    public UpdateCustomer() {
        try{
        initComponents();
//        this.setResizable(false);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Hotel Management System");
        s=(JOptionPane.showInputDialog("Enter Customer Id to Update")).trim();
        Class.forName("com.mysql.cj.jdbc.Driver");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel","root","root");
        stat=cn.createStatement();
        rs=stat.executeQuery("select * from customer where c_id="+s+"");
        if(rs.first())
        {
            this.setVisible(true);
            rs.first();
                jTextField1.setText(""+rs.getInt(1));
                jTextField3.setText(rs.getString(2));
                jTextField5.setText(rs.getString(3));
                jTextArea1.setText(rs.getString(4));
                comboAdd();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Customer Not Found.");
            this.dispose();
            new CustomerInformation().setVisible(true);
            
        }
        }
        catch(NullPointerException nex){this.dispose();new CustomerInformation().setVisible(true);}
        catch(SQLSyntaxErrorException se){JOptionPane.showMessageDialog(null,"Enter Valid Input", "", JOptionPane.ERROR_MESSAGE);}
        catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
    }
    void comboAdd()
    {
        try{
        rs=stat.executeQuery("select phone_no from c_phone_no where c_id="+s.trim()+"");
            while(rs.next())
            {
                jComboBox1.addItem(""+rs.getString(1));
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null,e);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("CUSTOMER ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 310, 200, 32);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("CUSTOMER NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 360, 200, 34);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("AADHAR NUMBER");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 410, 200, 32);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(700, 310, 650, 32);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 460, 192, 36);

        jTextField3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(700, 360, 650, 32);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(700, 460, 650, 100);

        jTextField5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(700, 410, 650, 32);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CUSTOMER INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 140, 500, 50);

        jButton1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(700, 673, 165, 50);

        jButton2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1030, 670, 170, 50);

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(700, 580, 265, 56);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("MOBILE NUMBER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(500, 580, 190, 56);

        jTextField2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(990, 580, 237, 60);

        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1250, 580, 100, 56);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1920, 1060);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        char z=evt.getKeyChar();
        String x;
        if(evt.getKeyCode()==10||evt.getKeyCode()==8||evt.getKeyCode()==16||evt.getKeyCode()==32)
        {
        }
        else if(z>='0'&&z<='9')
        {
            x=jTextField1.getText();
            jTextField1.setText(x);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Only Number Input");
            jTextField1.setText("");        // TODO add your handling code here:
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        char z=evt.getKeyChar();
        String x;
        if(evt.getKeyCode()==10||evt.getKeyCode()==8||evt.getKeyCode()==16||evt.getKeyCode()==32)
        {
        }
        else if(z>='a'&&z<='z'||z>='A'&&z<='Z')
        {
            x=jTextField3.getText();
            jTextField3.setText(x);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Only Character Input");
            jTextField3.setText("");        // TODO add your handling code here:
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        char z=evt.getKeyChar();
        String x;
        if(evt.getKeyCode()==10||evt.getKeyCode()==8||evt.getKeyCode()==16||evt.getKeyCode()==32)
        {
        }
        else if(z>='0'&&z<='9')
        {
            x=jTextField5.getText();
            jTextField5.setText(x);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Only Number Input");
            jTextField5.setText("");        // TODO add your handling code here:
        }    // TODO add your handling code here:

    }//GEN-LAST:event_jTextField5KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(count>0)
        {
            JOptionPane.showMessageDialog(null,"Press the Update Button First");
        }

        else
        {
    this.dispose();
    new CustomerInformation().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
        
        String c_name,c_aadhar,c_address;
                
                c_name=jTextField3.getText();
                c_aadhar=jTextField5.getText();
                c_address=jTextArea1.getText();
        
        if(c_name.trim().length()==0||c_aadhar.trim().length()==0||c_address.trim().length()==0)
            JOptionPane.showMessageDialog(null,"Enter all Information!");
        else
        {
            stat.executeUpdate("update customer set c_name='"+c_name+"',c_aadhar='"+c_aadhar+"',c_address='"+c_address+"' where c_id="+s+"");
            JOptionPane.showMessageDialog(null,"Information Updated Successfully!","",JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new CustomerInformation().setVisible(true);
        }
        
    }catch(Exception e){JOptionPane.showMessageDialog(null, e);
            this.dispose();
            new CustomerInformation().setVisible(true);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        jTextField2.setText("");
        jTextField2.setText(""+jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
            char z=evt.getKeyChar();
        String x;
    if(evt.getKeyCode()==10||evt.getKeyCode()==8||evt.getKeyCode()==16||evt.getKeyCode()==32)
    {
    }
    else if(z>='0'&&z<='9')
    {
        x=jTextField2.getText();
        jTextField2.setText(x);
    }
    else
    {
         JOptionPane.showMessageDialog(null,"Only Number Input");
         jTextField2.setText("");            // TODO add your handling code here:
    }    

    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            count=1;
        String f,l;
        f=jTextField2.getText().trim();l=((String)jComboBox1.getSelectedItem()).trim();
        if(f.length()!=10)
            JOptionPane.showMessageDialog(null,"Enter Valid Mobile Number");
        else
        {
        stat.executeUpdate("update c_phone_no set phone_no="+f+" where phone_no="+l+" and c_id="+s+"");
        jComboBox1.removeAllItems();
        comboAdd();
        }
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                new UpdateCustomer();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
